// <auto-generated />
using System;
using CStoValuation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CStoValuation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("CStoValuation.Core.Models.PriceHistoryPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DateUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketHashName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MarketHashName", "DateUtc");

                    b.ToTable("PriceHistoryPoints", (string)null);
                });

            modelBuilder.Entity("CStoValuation.Core.Models.PriceSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Listings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketHashName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Mean")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Median")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Min")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TakenUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MarketHashName", "TakenUtc");

                    b.ToTable("PriceSnapshots", (string)null);
                });

            modelBuilder.Entity("CStoValuation.Infrastructure.Persistence.Entities.CachedInventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CachedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Exterior")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketHashName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Marketable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SteamId64")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Tradable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Weapon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SteamId64");

                    b.ToTable("CachedInventoryItems", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
